name: Run checks

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  npm-install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Use cache for npm 🎁
        id: cache-npm
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install npm packages 📦
        run: |
          npm ci
